#
# Overrides
#
AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
CollectionMethods:
  PreferredMethods:
    find_all: 'select'
GlobalVars:
  AllowedVariables:
  - $log
  - $rails_log
  - $vim_log
  - $rhevm_log
  - $aws_log
  - $fog_log
HashSyntax:
  EnforcedStyle: hash_rockets
LineLength:
  Max: 120
RedundantReturn:
  AllowMultipleReturnValues: true
SignalException:
  EnforcedStyle: only_raise
SingleLineMethods:
  AllowIfMethodIsEmpty: false
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
#
# Enabled/Disabled
#
Documentation:
  Enabled: false
Encoding:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingComma:
  Enabled: false
